swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API de Votação'
  description: 'API para gerenciar sessões de votação'
host: 'http://ec2-3-91-44-100.compute-1.amazonaws.com'
basePath: ':8080'
schemes:
  - 'http'
definitions:
  DadosCadastroAssociado:
    type: 'object'
    properties:
      nome:
        type: 'string'
        example: 'Alice Baldez'
      cpf:
        type: 'string'
        example: '548.190.280-06'
      votante:
        type: 'boolean'
        example: true
  Associado:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      nome:
        type: 'string'
      cpf:
        type: 'string'
      votante:
        type: 'boolean'
  DadosCadastroPauta:
    type: 'object'
    properties:
      titulo:
        type: 'string'
        example: 'Cadastrar Pauta'
      descricao:
        type: 'string'
        example: 'Descrição Pauta'
      votacaoInicio:
        type: 'string'
        format: 'date'
        example: '2024-06-17'
      votacaoFim:
        type: 'string'
        format: 'date'
        example: '2024-06-29'
  DadosCadastroRegistroVotacao:
    type: 'object'
    properties:
      associadoId:
        type: 'string'
        example: '1'
      pautaId:
        type: 'string'
        example: '1'
      voto:
        type: 'boolean'
        example: true
paths:
  /sessions:
    post:
      summary: 'Cadastrar novo associado'
      operationId: 'cadastrarAssociado'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados do associado a ser cadastrado'
          required: true
          schema:
            $ref: '#/definitions/DadosCadastroAssociado'
      responses:
        '201':
          description: 'Associado criado com sucesso'
          schema:
            $ref: '#/definitions/Associado'
        '400':
          description: 'Requisição inválida'
  /pauta:
    post:
      summary: 'Cadastrar nova pauta'
      operationId: 'cadastrarPauta'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados da pauta a ser cadastrada'
          required: true
          schema:
            $ref: '#/definitions/DadosCadastroPauta'
      responses:
        '200':
          description: 'Pauta criada com sucesso'
        '400':
          description: 'Requisição inválida'
  /registro-votacao:
    post:
      summary: 'Cadastrar novo registro de votação'
      operationId: 'cadastrarRegistroVotacao'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados do registro de votação a ser cadastrado'
          required: true
          schema:
            $ref: '#/definitions/DadosCadastroRegistroVotacao'
      responses:
        '200':
          description: 'Registro de votação criado com sucesso'
        '400':
          description: 'Requisição inválida'
  /registro-votacao/pauta/{idPauta}/associado/{idAssociado}:
    get:
      summary: 'Buscar registro de votação por pauta e associado'
      operationId: 'buscarRegistroVotacaoPorPautaEAssociado'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: 'idPauta'
          required: true
          type: 'integer'
          format: 'int64'
          description: 'ID da pauta'
        - in: 'path'
          name: 'idAssociado'
          required: true
          type: 'integer'
          format: 'int64'
          description: 'ID do associado'
      responses:
        '200':
          description: 'Registro de votação encontrado com sucesso'
          schema:
            type: 'object'
            properties:
              id:
                type: 'integer'
                format: 'int64'
              associadoId:
                type: 'string'
              pautaId:
                type: 'string'
              voto:
                type: 'boolean'
        '400':
          description: 'Requisição inválida'
        '404':
          description: 'Registro de votação não encontrado'